# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('plural', models.CharField(max_length=200)),
                ('image_src', models.CharField(max_length=200)),
                ('item_id', models.IntegerField(default=0)),
                ('desc_id', models.CharField(max_length=200)),
                ('autosell', models.IntegerField(default=0)),
            ],
        ),
    ]
