# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kolofflinewiki', '0002_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_type', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_1', to='kolofflinewiki.Item'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_2', to='kolofflinewiki.Item'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='kolofflinewiki.Item'),
        ),
    ]
