# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kolofflinewiki', '0003_auto_20170924_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe_type',
            fields=[
                ('type_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kolofflinewiki.Recipe_type'),
        ),
    ]
